#!/usr/bin/python37all
import cgi
import json
data = cgi.FieldStorage()
sounds = data.getvalue('sounds') 
mhours = data.getvalue('mhours') 
nhours = data.getvalue('nhours') 
rhours = data.getvalue('rhours') 
mmins = data.getvalue('mmin') 
nmins = data.getvalue('nmin') 
rmins = data.getvalue('rmin') 
mtime = data.getvalue('mtime')
ntime = data.getvalue('ntime') 
rtime = data.getvalue('rtime') 
###import calendar data potentially to display dates
web = {"sounds":sounds, "mhours":mhours, "nhours":nhours, "rhours":rhours, "mmin":mmin, "nmin":nmin, "rmin":rmin, "mtime":mtime, "ntime":ntime, "rtime":rtime}
with open('final.txt', 'w') as f:
  json.dump(web,f) 

print('Content-type:text/html\n\n')
print('<html>')
print('<div>')
print('<div style="width: 600px; background: #40E0D0; border: 1px; text-align: center;"><br />')
print('<h2>ENME441 Smart Alarm</h2>')
print('<p style="font-size: 1.5em;"><strong>Input in your preferences</strong></p>')
print('<div style="width: 600px; background: #b0e0e6; border: 1px; text-align: center;"><br />')
print('<form action="/cgi-bin/finalproject.py" method="POST">')
print('<label for="sounds">Choose Sound: </label><select id="sounds" name="sounds">')
print('<option value="sound1">Sound 1</option>')
print('<option value="sound2">Sound 2</option>')
print('<option value="sound3">Sound 3</option>')
print('<option value="sound4">Sound 4</option>')
print('</select><br /><br />How Early to Wake Up Before Event:<select name="mhours">')
print('<option value="1">1</option>')
print('<option value="2">2</option>')
print('<option value="3">3</option>')
print('<option value="4">4</option>')
print('<option value="5">5</option>')
print('<option value="6">6</option>')
print('<option value="7">7</option>')
print('<option value="8">8</option>')
print('<option value="9">9</option>')
print('<option value="10">10</option>')
print('<option value="11">11</option>')
print('<option value="12">12</option>')
print('</select><select name="mmin">')
print('<option value="0">0</option>')
print('<option value="15">15</option>')
print('<option value="30">30</option>')
print('<option value="45">45</option>')
print('</select><select name="mtime">')
print('<option value="am">AM</option>')
print('<option value="pm">PM</option>')
print('</select><br /><br />When to set the bedtime alarm:<select name="nhours">')
print('<option value="1">1</option>')
print('<option value="2">2</option>')
print('<option value="3">3</option>')
print('<option value="4">4</option>')
print('<option value="5">5</option>')
print('<option value="6">6</option>')
print('<option value="7">7</option>')
print('<option value="8">8</option>')
print('<option value="9">9</option>')
print('<option value="10">10</option>')
print('<option value="11">11</option>')
print('<option value="12">12</option>')
print('</select><select name="nmin">')
print('<option value="0">0</option>')
print('<option value="15">15</option>')
print('<option value="30">30</option>')
print('<option value="45">45</option>')
print('</select><select name="ntime">')
print('<option value="am">AM</option>')
print('<option value="pm">PM</option>')
print('</select><br /><br />When to Refresh:<select name="rhours">')
print('<option value="1">1</option>')
print('<option value="2">2</option>')
print('<option value="3">3</option>')
print('<option value="4">4</option>')
print('<option value="5">5</option>')
print('<option value="6">6</option>')
print('<option value="7">7</option>')
print('<option value="8">8</option>')
print('<option value="9">9</option>')
print('<option value="10">10</option>')
print('<option value="11">11</option>')
print('<option value="12">12</option>')
print('</select><select name="rmin">')
print('<option value="0">0</option>')
print('<option value="15">15</option>')
print('<option value="30">30</option>')
print('<option value="45">45</option>')
print('</select><select name="rtime">')
print('<option value="am">AM</option>')
print('<option value="pm">PM</option>')
print('</select><br /><br /><input type="submit" value="Submit Changes" />')
print('</form>')
print('</div>')
print('</div>')
print('</div>')
print('</html>')